# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
test:
  adapter: postgresql
  encoding: unicode
  database: tur_test_test
  pool: 5
  username: postgres
  password: 15mav00
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: tur_test_dev
  pool: 5
  username: postgres
  password: 15mav00
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: tur_test_prod
  pool: 5
  username: postgres
  password: 15mav00
  timeout: 5000